data:
  dataset: "lfm"
  batch_size: 512
  normalize_data: False
  embedding_dimension: "musicnn"

model:
  hidden_dimensions: [256, 128]
  latent_dimension: 64
  num_codebook_layers: 3
  codebook_clusters: 256
  commitment_weight: 0.25

train:
  learning_rate: 0.001
  weight_decay: 0.0
  num_epochs: 1024
  warmup_epochs: 50
  validation_step: 50
  metric_eval_samples: 50000

general:
  seed: 2026
  use_wandb: True
  wandb_project: "semantic_id_lfm_musicnn"
  wandb_entity: "justin-hangoebl-master-thesis"
