from hopwise.model.path_language_modeling_recommender.kgglm import KGGLM
from hopwise.model.path_language_modeling_recommender.pearlm import PEARLM
from hopwise.model.path_language_modeling_recommender.plm import PLM
from hopwise.model.path_language_modeling_recommender.sprig import SPRIG