# @Time   : 2026/01
# @Author : Justin Hangoebl
# @Email  : hangoebl.j@gmail.com

r"""KIGER
##################################################
KIGER is an extension of KGGLM that uses semantic IDs for items instead of 
random indices. Semantic IDs are generated by an RQ-VAE model and provide a 
more meaningful representation of items (e.g., SEM1, SEM2, ..., SEM256 instead 
of ITEM0, ITEM1, ..., ITEM15999).

The key difference from KGGLM:
- Items are represented using semantic ID tokens (multiple semantic tokens per item)
- Users, entities, and relations still use regular index-based tokens
- Requires a .semanticids file mapping items to their semantic ID sequences
"""

from hopwise.model.path_language_modeling_recommender.kgglm import KGGLM
from hopwise.model.sequence_postprocessor import SemanticSequencePostProcessor



class KIGER(KGGLM):
    r"""KIGER extends KGGLM by using semantic IDs for item representation.
    
    Instead of using simple item indices (ITEM0, ITEM1, ...), KIGER represents each item 
    as a sequence of semantic tokens (SEM1, SEM2, SEM69, ...). This semantic representation 
    is learned by an RQ-VAE model and provides better generalization.
    
    The model expects:
    - A dataset that provides semantic ID mappings via a .semanticids file
    - The semantic ID mapping converts each item to a sequence of semantic tokens
    - Users, relations, and non-item entities continue to use standard indexing
    
    Note: The dataset must be a KnowledgePathSemanticIDDataset or similar that 
    provides the semantic ID vocabulary in the tokenizer.
    """
    
    TRAIN_STAGES = ["pretrain", "finetune"]

    def __init__(self, config, dataset):
        # The dataset should already have initialized the tokenizer with semantic IDs
        # Check if semantic IDs are available
        if not hasattr(dataset, 'semantic_id_mapping'):
            raise ValueError(
                "KIGER requires a dataset with semantic ID mappings. "
                "Please use KnowledgePathSemanticIDDataset or ensure your dataset "
                "has loaded the .semanticids file and initialized the tokenizer accordingly."
            )
        
        # Store semantic ID configuration
        self.num_semantic_tokens = config["num_semantic_tokens"]
        self.semantic_ids_per_item = config["semantic_ids_per_item"]
        
        # Initialize parent (KGGLM) which will use the dataset's tokenizer
        # The tokenizer should already contain semantic ID tokens instead of item tokens
        super().__init__(config, dataset)
        
        self.logger.info(
            f"KIGER initialized with {self.num_semantic_tokens} semantic tokens, "
            f"{self.semantic_ids_per_item} tokens per item"
        )
        self.sequence_postprocessor = SemanticSequencePostProcessor(
            tokenizer=dataset.tokenizer,
            used_ids=dataset.get_user_used_ids(),
            item_num=dataset.item_num,
            reverse_semantic_mapping=dataset.get_reverse_semantic_mapping(),
            semantic_ids_per_item=self.semantic_ids_per_item,
            topk=config["topk"],
        )
        